version: "3.8"

services:
  glpi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: glpi-web
    restart: always
    ports:
      - "80:80"  # Puedes cambiar el puerto si es necesario
    volumes:
      - ./glpi:/var/www/html
      - ./volumes/glpi-files:/var/www/html/files
      - ./backups:/backups
      - ~/.config/rclone:/root/.config/rclone:ro  # Configuración de rclone (OneDrive, Google Drive, etc)
      - ./docker/custom-php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./docker/crontab:/etc/cron.d/glpi-cron  # Cron personalizado
      - ./scripts:/var/www/html/scripts  # Scripts de backup y restauración
    environment:
      - TZ=America/Bogota
    depends_on:
      - db
    command: ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]

  db:
    image: mariadb:10.11
    container_name: glpi-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=glpi
      - MYSQL_USER=glpi
      - MYSQL_PASSWORD=glpipass
      - TZ=America/Bogota
    volumes:
      - ./volumes/db-data:/var/lib/mysql
